apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodbchallenge8-deployment
  namespace: hmahjoub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodbchallenge8
  template:
    metadata:
      labels:
        app: mongodbchallenge8
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        command: ["mongod", "--bind_ip", "0.0.0.0"] # Désactive l'authentification
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodbchallenge8-service
  namespace: hmahjoub
spec:
  selector:
    app: mongodbchallenge8
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
